#!/usr/bin/python3
help = """
MaxRename by Tubbadu

usage:
 maxrename 'path/to/file1' 'path/to/file2' 'path/to/file3' ... 'path/to/fileN'
 
 than insert the new name (without the path!), including the # char, which will be replaced by increasing numbers, in the same order as they has been called in maxrename.
"""
import glob
import os
import sys

if(len(sys.argv) <= 1):
	print("erroreeee")
elif sys.argv[1] == '-h' or sys.argv[1] == '-help':
	print(help)
else:
	newnames = input("Insert new name (the '#' char will be replaced with crescent numbers):\n")
	if "#" in newnames:
		print("<", sys.argv[1], ">")
		lista = list(sys.argv[1:])
		c = 0
		length = len(str(len(lista))) # numero di cifre da mettere
		for el in lista:
			c += 1
			num = "0" * (length - len(str(c))) + str(c)
			oldname = el.split("/")
			oldname[-1] = newnames.replace("#", num)
			newname = ""
			for substr in oldname:
				newname += substr + "/"
			newname = newname[:-1]
			print(el, "->", newname)
			os.rename(el, newname)
			
	else:
		print("error: new name must include '#' char")
